version: '3.1'

services:
  linuxfr.org:
    build:
      context: .
      dockerfile: deployment/linuxfr.org/Containerfile
    env_file:
      - deployment/default.env
    volumes:
      # Share host directories so, the developer can edit them
      # and see the result without need to restart the container
      - ./app:/linuxfr.org/app:Z
      - ./db:/linuxfr.org/db:Z
      - ./lib:/linuxfr.org/lib:Z
      - ./public:/linuxfr.org/public:Z
      - ./test:/linuxfr.org/test:Z
      # uploads are shared with the nginx service
      - data-uploads:/linuxfr.org/uploads
    tmpfs:
      - /linuxfr.org/public/tmp:size=100M
    healthcheck:
      test: curl --fail http://localhost:3000
    depends_on:
      database:
        condition: service_completed_successfully
        restart: true
      redis:
        condition: service_completed_successfully
        restart: true

  linuxfr-board:
    build:
      context: deployment/linuxfr-board
    env_file:
      - deployment/default.env
    healthcheck:
      test: curl --fail -I http://localhost:9000
    depends_on:
      redis:
        condition: service_completed_successfully
        restart: true

  linuxfr-img:
    build:
      context: deployment/linuxfr-img
    env_file:
      - deployment/default.env
    healthcheck:
      test: curl --fail http://localhost:8000/status
    depends_on:
      redis:
        condition: service_completed_successfully
        restart: true
    volumes:
      - cache-img:/linuxfr-img/cache

  nginx:
    image: docker.io/nginx:stable
    env_file:
      - deployment/default.env
    volumes:
      - ./deployment/nginx/templates:/etc/nginx/templates:Z
      - ./public/fonts:/var/linuxfr/fonts:Z
      - data-uploads:/var/linuxfr/uploads
    ports:
      - target: 80
        published: 127.0.0.1:80
        protocol: tcp
    depends_on:
      linuxfr.org:
        condition: service_completed_successfully
        restart: true
      linuxfr-board:
        condition: service_completed_successfully
        restart: true
      linuxfr-img:
        condition: service_completed_successfully
        restart: true

  database:
    build:
      context: deployment/database
    env_file:
      - deployment/default.env
    ports:
      - target: 3306
        published: 127.0.0.1:3306
        protocol: tcp
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    volumes:
      - data-database:/var/lib/mysql

  redis:
    image: docker.io/redis:5
    healthcheck:
      test: redis-cli --raw incr ping
    volumes:
      - data-redis:/data

volumes:
  data-database:
    driver: local
  data-redis:
    driver: local
  data-uploads:
    driver: local
  cache-img:
    driver: local

