version: '3.1'

services:
  linuxfr.org:
    build:
      context: .
      dockerfile: deployment/linuxfr.org/Dockerfile
    env_file:
      - deployment/default.env
    volumes:
      # Share host directories so, the developer can edit them
      # and see the result without need to restart the container
      - ./app:/linuxfr.org/app
      - ./db:/linuxfr.org/db
      - ./public:/linuxfr.org/public
      - ./test:/linuxfr.org/test
      # uploads are shared with the nginx service
      - data-uploads:/linuxfr.org/uploads
    tmpfs:
      - /linuxfr.org/public/tmp:size=100M
    depends_on:
      - database
      - redis

  linuxfr-board:
    build:
      context: deployment/linuxfr-board
    env_file:
      - deployment/default.env
    depends_on:
      - redis

  linuxfr-img:
    build:
      context: deployment/linuxfr-img
    env_file:
      - deployment/default.env
    depends_on:
      - redis
    volumes:
      - cache-img:/linuxfr-img/cache

  nginx:
    image: nginx:stable
    env_file:
      - deployment/default.env
    volumes:
      - ./deployment/nginx/templates:/etc/nginx/templates
      - ./public/fonts:/var/linuxfr/fonts
      - data-uploads:/var/linuxfr/uploads
    ports:
      - "80:80"
    depends_on:
      - linuxfr.org
      - linuxfr-board
      - linuxfr-img

  database:
    build:
      context: deployment/database
    env_file:
      - deployment/default.env
    ports:
      - "3306:3306"
    volumes:
      - data-database:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
      - data-redis:/data

volumes:
  data-database:
    driver: local
  data-redis:
    driver: local
  data-uploads:
    driver: local
  cache-img:
    driver: local

