version: '3.1'

services:
  linuxfr.org:
    build:
      context: .
      dockerfile: deployment/linuxfr.org/Dockerfile
    env_file:
      - deployment/default.env
    # Share host directories so, the developer can edit them
    # and see the result without need to restart the container
    volumes:
      - ./app:/linuxfr.org/app
      - ./db:/linuxfr.org/db
      - ./public:/linuxfr.org/public
    depends_on:
      - database
      - database-test
      - redis

  linuxfr-board:
    build:
      context: deployment/linuxfr-board
    env_file:
      - deployment/default.env
    depends_on:
      - redis

  linuxfr-img:
    build:
      context: deployment/linuxfr-img
    env_file:
      - deployment/default.env
    depends_on:
      - redis
    volumes:
      - cache-img:/linuxfr-img/cache

  nginx:
    image: nginx:stable
    volumes:
      - ./deployment/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - linuxfr.org
      - linuxfr-board
      - linuxfr-img

  database:
    image: mariadb:10.1
    env_file:
      - deployment/default.env
    restart: always
    volumes:
      - data-database:/var/lib/mysql

  database-test:
    image: mariadb:10.1
    env_file:
      - deployment/default.env
    entrypoint: ["/linuxfr-database-test-entrypoint.sh"]
    command: ["mysqld"]
    restart: always
    volumes:
      - data-database-test:/var/lib/mysql
      - ./deployment/linuxfr-database-test-entrypoint.sh:/linuxfr-database-test-entrypoint.sh

  redis:
    image: redis:5
    restart: always
    volumes:
      - data-redis:/data

volumes:
  data-database:
    driver: local
  data-database-test:
    driver: local
  data-redis:
    driver: local
  cache-img:
    driver: local

