FROM docker.io/debian:buster-slim as build

LABEL org.opencontainers.image.title="LinuxFr.org image caching service"
LABEL org.opencontainers.image.description="Store external images into a cache to not flood external website"
LABEL org.opencontainers.image.source="https://github.com/linuxfrorg/img-LinuxFr.org"
LABEL org.opencontainers.image.url="https://github.com/linuxfrorg/linuxfr.org/blob/master/Container.md"
LABEL org.opencontainers.image.licenses="AGPL-3.0-only"
LABEL org.opencontainers.image.version="buster:1.0"
LABEL org.opencontainers.image.authors="Adrien Dorsaz <adrien@adorsaz.ch>"

ENV GOPATH=/linuxfr-img
WORKDIR /linuxfr-img

# Build linuxfr-img
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    golang git ca-certificates \
  && apt-get clean \
  && go get -u github.com/linuxfrorg/img-LinuxFr.org

FROM debian:bullseye-slim as deploy

ARG UID=1200

WORKDIR /linuxfr-img

# Create linuxfr.org user
RUN useradd --uid ${UID} --no-create-home linuxfr.org \
  && chown ${UID}:0 /linuxfr-img \
  && chmod 770  /linuxfr-img

USER ${UID}

COPY --from=build --chown=${UID}:0 --chmod=770 /linuxfr-img/bin/img-LinuxFr.org .

EXPOSE 8000

CMD ["sh", "-c", "exec ./img-LinuxFr.org -a 0.0.0.0:8000 -r \"${REDIS_URL##redis://}\""]
