FROM docker.io/ruby:2-slim-buster

LABEL org.opencontainers.image.title="LinuxFr.org boards"
LABEL org.opencontainers.image.description="Chat rooms for LinuxFr"
LABEL org.opencontainers.image.source="https://github.com/linuxfrorg/board-sse-linuxfr.org"
LABEL org.opencontainers.image.url="https://github.com/linuxfrorg/linuxfr.org/blob/master/Container.md"
LABEL org.opencontainers.image.licenses="AGPL-3.0-only"
LABEL org.opencontainers.image.version="buster:1.0"
LABEL org.opencontainers.image.authors="Adrien Dorsaz <adrien@adorsaz.ch>"

ARG UID=1200

WORKDIR /linuxfr-board

RUN apt-get update \
  # Install dependencies \
  && apt-get install -y --no-install-recommends \
    build-essential ruby ruby-dev \
  && apt-get clean \
  # Create linuxfr.org user \
  && useradd --uid ${UID} --no-create-home linuxfr.org \
  && chown ${UID}:0 /linuxfr-board \
  && chmod 770  /linuxfr-board

# Install board-linuxfr
USER ${UID}
RUN gem install board-linuxfr -v '~> 0.1.3'

USER 0
RUN apt purge --autoremove -y build-essential ruby-dev

USER ${UID}
EXPOSE 9000

CMD ["board-linuxfr"]
